# python harjoituksia 5.4.2023
print("SYÖTÄ HENKILÖTIEDOT")
print("-------------------")
print( )
etunimet = input("Anna etunimet: ")
sukunimi = input("Anna sukunimi: ")
puh = input("Anna puhelinnumero: ")
sposti = input("Anna sähköpostiosoite: ")
osoite = input("Anna lähiosoite: ")
postinro = input("Anna postinumero: ")
kaupunki = input("Anna kaupunki: ")
maa = input("Anna maa: ")
svuosi = int(input("Anna syntymävuosi: "))
print( )
print("KIITOS!")
print( )
print( )
print("HENKILÖN TIEDOT")
print("-------------------")
print( )
print("NIMI:")
print("  " + sukunimi + "," + etunimet)
print("PUH:")
print("  " + puh)
print("E-MAIL:")
print("  " + sposti)
print("OSOITE:")
print("  " + osoite)
print("  " + postinro + " " + kaupunki)
print("  " + maa)
print(f"Ikä: {2023 - svuosi}" )

